export type SeedMessage = {
  key: string
  role: 'user' | 'assistant'
  content: string
  reasoning?: string
  activities?: Record<string, unknown>[]
  model?: 'gpt-5.6-sol' | 'gpt-5.6-luna'
  reasoningEffort?: 'low' | 'medium' | 'high' | 'xhigh' | 'max'
  speed?: 'standard' | 'fast'
  minuteOffset: number
}

export type SeedConversation = {
  key: string
  title: string
  daysAgo: number
  messages: SeedMessage[]
}

const markdown = (...lines: string[]) => lines.join('\n')

export const seedConversations: SeedConversation[] = [
  {
    key: 'markdown-reference',
    title: 'Markdown component reference',
    daysAgo: 0,
    messages: [
      {
        key: 'request-reference',
        role: 'user',
        content: 'Create a compact Markdown reference that exercises every element our chat renderer supports.',
        minuteOffset: 0,
      },
      {
        key: 'reference-response',
        role: 'assistant',
        reasoning: 'I organized the examples by reading pattern so the rendered result is easy to scan.',
        content: markdown(
          '# Markdown reference',
          '',
          'This response combines **strong emphasis**, *subtle emphasis*, ~~removed text~~, and `inline code` in one complete example.',
          '',
          '> A useful interface makes structure visible without making the content feel heavy.',
          '',
          '## Lists',
          '',
          '- Keep each item focused.',
          '- Use a nested item when it adds context:',
          '  - preserve semantic order;',
          '  - keep labels concise.',
          '- Finish with an explicit outcome.',
          '',
          '1. Inspect the current state.',
          '2. Make the smallest coherent change.',
          '3. Verify the complete user flow.',
          '',
          '- [x] Persist the conversation',
          '- [x] Render GitHub-flavored Markdown',
          '- [ ] Review the result in both appearances',
          '',
          '## Comparison',
          '',
          '| Element | Best use | Example |',
          '| --- | --- | --- |',
          '| Paragraph | Explanation | A complete thought |',
          '| List | Related items | Requirements or steps |',
          '| Table | Exact comparison | Options and tradeoffs |',
          '| Code block | Runnable material | Commands or source |',
          '',
          '## TypeScript',
          '',
          '```typescript',
          'type Release = {',
          '  ready: boolean',
          '  checks: string[]',
          '}',
          '',
          'const release: Release = {',
          '  ready: true,',
          "  checks: ['lint', 'typecheck', 'test'],",
          '}',
          '```',
          '',
          '## Command',
          '',
          '```bash',
          'npm run verify',
          '```',
          '',
          '---',
          '',
          'For the syntax rules, see the [CommonMark specification](https://spec.commonmark.org/).',
        ),
        model: 'gpt-5.6-sol',
        reasoningEffort: 'medium',
        speed: 'standard',
        minuteOffset: 1,
      },
      {
        key: 'request-structured-examples',
        role: 'user',
        content: 'Add realistic JSON and diff examples, then summarize what changed.',
        minuteOffset: 4,
      },
      {
        key: 'structured-response',
        role: 'assistant',
        reasoning: 'I used small valid samples so copy, syntax highlighting, and horizontal overflow can all be checked.',
        content: markdown(
          '## JSON payload',
          '',
          '```json',
          '{',
          '  "conversationId": "local-only",',
          '  "status": "completed",',
          '  "features": ["markdown", "history", "streaming"]',
          '}',
          '```',
          '',
          '## Focused diff',
          '',
          '```diff',
          '- const persistence = "provider"',
          '+ const persistence = "application database"',
          '```',
          '',
          'The example now covers:',
          '',
          '- a structured object with a list;',
          '- a compact before-and-after change;',
          '- long-form Markdown rendered from a persisted assistant message.',
        ),
        model: 'gpt-5.6-sol',
        reasoningEffort: 'medium',
        speed: 'standard',
        minuteOffset: 5,
      },
    ],
  },
  {
    key: 'research-summary',
    title: 'Research a resilient chat history',
    daysAgo: 1,
    messages: [
      {
        key: 'request-research',
        role: 'user',
        content: 'Research the main properties of a resilient persisted chat history and give me a practical recommendation.',
        minuteOffset: 0,
      },
      {
        key: 'research-response',
        role: 'assistant',
        reasoning: 'I compared the application persistence boundary with the provider request boundary and kept the recommendation implementation-oriented.',
        activities: [
          {
            id: 'seed-search-persistence',
            type: 'search',
            query: 'persisted chat history application database provider message identifiers',
            results: [
              {
                id: 'postgres-transactions',
                title: 'PostgreSQL transaction processing',
                domain: 'postgresql.org',
                url: 'https://www.postgresql.org/docs/current/tutorial-transactions.html',
              },
              {
                id: 'openai-data-controls',
                title: 'OpenAI API data controls',
                domain: 'platform.openai.com',
                url: 'https://platform.openai.com/docs/guides/your-data',
              },
            ],
          },
        ],
        content: markdown(
          'A resilient chat history should have four properties:',
          '',
          '1. **Application-owned identity.** Conversation and message IDs belong to the product database.',
          '2. **Complete transcripts.** A continuation sends ordered `user` and completed `assistant` content.',
          '3. **Atomic writes.** The user message and placeholder assistant turn are created together.',
          '4. **Recoverable streaming.** Partial output is saved when a request fails or is cancelled.',
          '',
          '### Recommendation',
          '',
          'Keep local UUIDs out of provider-specific continuation fields. Rebuild each request from persisted roles and content, and treat provider response IDs as optional metadata only if a future feature explicitly needs them.',
        ),
        model: 'gpt-5.6-sol',
        reasoningEffort: 'high',
        speed: 'standard',
        minuteOffset: 2,
      },
      {
        key: 'request-risk',
        role: 'user',
        content: 'What is the concrete failure mode if local message IDs are mistaken for provider response IDs?',
        minuteOffset: 6,
      },
      {
        key: 'risk-response',
        role: 'assistant',
        content: markdown(
          'The provider would try to resolve an identifier it never created. The continuation could then fail before generation starts, even though the local transcript is valid.',
          '',
          '**Safe boundary:**',
          '',
          '- local UUIDs identify database rows and UI elements;',
          '- the model request contains only ordered roles and content;',
          '- provider storage remains disabled unless the architecture deliberately changes.',
        ),
        model: 'gpt-5.6-luna',
        reasoningEffort: 'low',
        speed: 'fast',
        minuteOffset: 7,
      },
    ],
  },
  {
    key: 'release-plan',
    title: 'Plan a reliable release',
    daysAgo: 4,
    messages: [
      {
        key: 'request-release-plan',
        role: 'user',
        content: 'Turn this feature into a release plan that another engineer can execute without guessing.',
        minuteOffset: 0,
      },
      {
        key: 'release-plan-response',
        role: 'assistant',
        reasoning: 'I ordered the plan by dependency and separated automated checks from rendered product verification.',
        activities: [
          {
            id: 'seed-step-contract',
            type: 'step',
            label: 'Confirm the persistence contract',
            status: 'complete',
            meta: 'Database and AI boundary',
          },
          {
            id: 'seed-step-tests',
            type: 'step',
            label: 'Run focused and integration checks',
            status: 'complete',
            meta: 'API, AI, and web',
          },
        ],
        content: markdown(
          '## Release plan',
          '',
          '### 1. Data contract',
          '',
          '- Apply the conversation migration.',
          '- Seed only completed alternating turns.',
          '- Confirm every seeded conversation can accept a new turn.',
          '',
          '### 2. Automated verification',
          '',
          '```bash',
          'npm run api:typecheck',
          'npm run api:test',
          'npm run api:test:integration',
          'npm run web:test',
          '```',
          '',
          '### 3. Product verification',
          '',
          '- Open conversations from every sidebar date group.',
          '- Inspect headings, lists, tables, links, and code blocks.',
          '- Continue one seeded conversation and reload the page.',
          '- Repeat at a narrow width and in dark appearance.',
        ),
        model: 'gpt-5.6-sol',
        reasoningEffort: 'high',
        speed: 'standard',
        minuteOffset: 2,
      },
      {
        key: 'request-release-gate',
        role: 'user',
        content: 'Give me a single release gate I can paste into the pull request.',
        minuteOffset: 5,
      },
      {
        key: 'release-gate-response',
        role: 'assistant',
        content: '> Release only after an idempotent seed run, a successful continuation from seeded history, the full repository verification, and rendered chat QA all pass.',
        model: 'gpt-5.6-sol',
        reasoningEffort: 'medium',
        speed: 'standard',
        minuteOffset: 6,
      },
    ],
  },
  {
    key: 'database-review',
    title: 'Review a PostgreSQL migration',
    daysAgo: 14,
    messages: [
      {
        key: 'request-database-review',
        role: 'user',
        content: 'Review this conversation schema for ordering, ownership, and concurrent streaming risks.',
        minuteOffset: 0,
      },
      {
        key: 'database-review-response',
        role: 'assistant',
        reasoning: 'I checked foreign-key ownership, deterministic ordering, and the partial unique index that serializes active turns.',
        activities: [
          {
            id: 'seed-tool-schema',
            type: 'tool',
            action: 'Reviewed',
            target: 'apps/api/src/db/schema.ts',
            additions: 0,
            deletions: 0,
          },
          {
            id: 'seed-trace-index',
            type: 'trace',
            kind: 'database',
            label: 'Checked active-turn constraint',
            detail: 'One streaming assistant message per conversation',
          },
        ],
        content: markdown(
          'The core shape is sound:',
          '',
          '- `conversations.user_id` establishes ownership and cascades deletion;',
          '- `messages.conversation_id` keeps the transcript relational;',
          '- `(created_at, id)` provides stable ordering when timestamps tie;',
          '- the partial unique index prevents two streaming assistant rows in one conversation.',
          '',
          'A representative guard looks like this:',
          '',
          '```text',
          'UNIQUE (conversation_id)',
          "WHERE role = 'assistant' AND status = 'streaming'",
          '```',
          '',
          'The transaction that creates a user turn and its assistant placeholder must also lock the owned conversation. That keeps application-level checks aligned with the database constraint.',
        ),
        model: 'gpt-5.6-sol',
        reasoningEffort: 'xhigh',
        speed: 'standard',
        minuteOffset: 3,
      },
      {
        key: 'request-database-order',
        role: 'user',
        content: 'Why use the ID as a secondary ordering key?',
        minuteOffset: 7,
      },
      {
        key: 'database-order-response',
        role: 'assistant',
        content: 'Two rows can share the same timestamp, especially in fixtures or bulk writes. Sorting by `created_at` and then by the UUID gives the query a stable total order instead of relying on PostgreSQL row-return order.',
        model: 'gpt-5.6-luna',
        reasoningEffort: 'low',
        speed: 'fast',
        minuteOffset: 8,
      },
    ],
  },
  {
    key: 'project-brief',
    title: 'Write a concise project brief',
    daysAgo: 45,
    messages: [
      {
        key: 'request-project-brief',
        role: 'user',
        content: 'Write a concise brief for a product that combines authentication, persistent conversations, and a separate AI runtime.',
        minuteOffset: 0,
      },
      {
        key: 'project-brief-response',
        role: 'assistant',
        content: markdown(
          '## myBot',
          '',
          'myBot is an authenticated AI workspace built around durable conversations. The web application presents a focused chat interface; the Node.js API owns users, sessions, conversations, and streaming persistence; and the Python service isolates model execution and provider-specific behavior.',
          '',
          'The architecture keeps product data under application control while allowing the AI boundary to evolve independently. Users can return to earlier work, continue a transcript, and recover completed output without depending on provider-hosted conversation state.',
        ),
        model: 'gpt-5.6-sol',
        reasoningEffort: 'medium',
        speed: 'standard',
        minuteOffset: 2,
      },
    ],
  },
]

export const seedMessageCount = seedConversations.reduce(
  (total, conversation) => total + conversation.messages.length,
  0,
)
